### ISSUE TITLE
client.ignoreSSLissues doesnt work

### ISSUE THREAD

**Issue by hsarmah09** [jgritman/httpbuilder#60]
I have been trying to use a gradle plugin to make some REST calls which uses httpbuilder in backend, and i need to ignore all the SSL issues, but this doesnt seem to work.

**Comment by stein321** [comment]
which version are you using?

**Comment by maxtar** [comment]
Yeah, i've got the same issue on 0.7 version:
```
Exception in thread "main" javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1066)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:506)
	at groovyx.net.http.RESTClient.get(RESTClient.java:119)
```

**Comment by valnaumov** [comment]
Same issue

```
org.codehaus.groovy.modules.http-builder:http-builder:0.7.1
oauth.signpost:signpost-core:1.2.1.2
oauth.signpost:signpost-commonshttp4:1.2.1.2
```

client.ignoreSSLIssues() throws

```
Caught: java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLSocketFactory.<init>(Lorg/apache/http/conn/ssl/TrustStrategy;Lorg/apache/http/conn/ssl/X509HostnameVerifier;)V
java.lang.NoSuchMethodError: org.apache.http.conn.ssl.SSLSocketFactory.<init>(Lorg/apache/http/conn/ssl/TrustStrategy;Lorg/apache/http/conn/ssl/X509HostnameVerifier;)V
    at groovyx.net.http.HTTPBuilder.ignoreSSLIssues(HTTPBuilder.java:938)
```

**Comment by itissid** [comment]
Try using 0.7.2...

**Comment by sshikov** [comment]
There is no 0.7.2. in central at the moment.

**Comment by sshikov** [comment]
I have another error with 0.7.1 - host is null somethere is apache http. Will try 0.7.2 also.

**Comment by sshikov** [comment]
Checked. I have no problems with 0.7.2 (just deploy it to central please).
