### ISSUE TITLE
Can't use ignoreSSLIssues in version 0.7.1

### ISSUE THREAD

**Issue by zcmgyu** [jgritman/httpbuilder#75]
Java 8:
IDE: IntelliJ IDEA
Gradle 3

I have problem with SSL issue

```
import groovyx.net.http.RESTClient

def client = new RESTClient()
client.ignoreSSLIssues()
def result = client.get([uri: "https://sacvo76l6b.execute-api.ap-northeast-1.amazonaws.com/"])
```
It throws below exception

> javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
> 
> 	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431)
> 	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
> 	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
> 	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
> 	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
> 	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
> 	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
> 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
> 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1066)
> 	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
> 	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
> 	at groovyx.net.http.RESTClient.get(RESTClient.java:119)
> 	at Test.getAuthCode_(Test.groovy:53)

Although I'm using ignoreSSLIssues(), it seems like not work for me.
PS: Uri works fine for me if i use Postman 

Could you have any idea? Thanks alot 🥇

**Comment by zcmgyu** [comment]
To resolve "javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated" issue
 I just import lastest version of httpclient to Gradle/Maven
`compile 'org.apache.httpcomponents:httpclient:4.5.3'`

It took me 2 days to resolves. I hope this will be helpful with someone like me.

**Comment by zcmgyu** [comment]
To resolve "javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated" issue
 I just import lastest version of httpclient to Gradle/Maven
`compile 'org.apache.httpcomponents:httpclient:4.5.3'`

It took me 2 days to resolves. I hope this will be helpful with someone like me.
Please close

**Comment by rtretyak** [comment]
I regret I didn't find this post 3 hours earlier. 
@zcmgyu Thanks for saving my sleep time today.
By the way, in my case it was enough just to update the httpClient. After update the ignoreSsl thing was no longer needed. I bet this is due to lack of SNI support in the earlier versions of apache httpClient
