### ISSUE TITLE
groovy 4 java.lang.NoClassDefFoundError: groovy/util/slurpersupport/GPathResult

### ISSUE THREAD

**Issue by sysmat** [jgritman/httpbuilder#93]
- groovy:4.0.7
- error:

```
Caught: java.lang.NoClassDefFoundError: groovy/util/slurpersupport/GPathResult
java.lang.NoClassDefFoundError: groovy/util/slurpersupport/GPathResult
	at groovyx.net.http.ParserRegistry.<init>(ParserRegistry.java:87)
	at groovyx.net.http.HTTPBuilder.<init>(HTTPBuilder.java:185)
	at groovyx.net.http.RESTClient.<init>(RESTClient.java:80)
	at Rest.run(Rest.groovy:30)
Caused by: java.lang.ClassNotFoundException: groovy.util.slurpersupport.GPathResult
```

**Comment by lpiatek** [comment]
+1

**Comment by Bert-R** [comment]
This project is dead. Don't expect anyone to upgrade it to Groovy 4, particularly because it adds very little to the standard ``URLConnection`` class.

If it helps: In [this commit](https://github.com/yonadev/yona-server/commit/bdde91f22649e720d7bbb086f29f65ec939cc94d#diff-c3eb12578f5b031c63121612c624d76525e93432656af1464693750e03fd1f98), you find what I have done to move away from ``http-builder``.
